import React from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//components
import Main from '../components/Main'
import Header from '../components/layouts/Header'
import Footer from '../components/layouts/Footer'

//@types
import { IDrink } from '../@types/drink'

interface IResponse {
  ListOfDrinks:{
    drinks:IDrink[]
  }
}

export const DrinksContext = React.createContext([] as IDrink[])

export default function Home(props:IResponse) {
  const {drinks}  = props.ListOfDrinks
console.log(drinks)
  return (
    <DrinksContext.Provider value={drinks}>
    <div >
      <Head>
        <title>Drinks App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Main />
      <Footer/>

    
    </div>
    </DrinksContext.Provider>

  )
}


export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('https://www.thecocktaildb.com/api/json/v1/1/search.php?s=margarita')
  const data = await res.json()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      ListOfDrinks:data,
    }
  }
}