import React from 'react'
import Head from 'next/head'


//components
import Main from '../components/Main'
import Header from '../components/layouts/Header'
import Footer from '../components/layouts/Footer'

//@types
import { IDrink,IDrinkContext } from '../@types/drink'

interface IResponse {
  ListOfDrinks:{
    drinks:IDrink[]
  }
}

export const DrinksContext = React.createContext({
  arrOfDrinks:[] as IDrink[],
  setArrOfDrinks:(prev:any)=>{}
})

export default function Home(props:IResponse) {
  const {drinks}  = props.ListOfDrinks
  const [arrOfDrinks,setArrOfDrinks] = React.useState(drinks)
  const value:IDrinkContext = {arrOfDrinks,setArrOfDrinks}

  return (
    <DrinksContext.Provider value={value}>
      <Head>
        <title>Drinks App</title>
        <meta name="simple app" content="Generated by MohammadHossein Jahanbakhsh" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      <Header/>
      <Main />
      <Footer/>

    
    </div>
    </DrinksContext.Provider>

  )
}


export async function getStaticProps() {
  const res = await fetch('https://www.thecocktaildb.com/api/json/v1/1/search.php?s=margarita')
  const data = await res.json()

  return {
    props: {
      ListOfDrinks:data,
    }
  }
}